services:
  database:
    container_name: movie-manager-db
    image: postgres:15-alpine
    restart: always
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

    volumes:
      - postgresql:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-init db.d/schema.sql

volumes:
  postgresql:
    driver: local

