package com.github.angel.utils;

public enum Genre {
    ACTION, ADVENTURE, COMEDY, DRAMA, FANTASY, HORROR, MUSICAL, ROMANCE, THRILLER, WESTERN,
    ANIMATION, DOCUMENTARY, SCIENCE_FICTION, FAMILY, MYSTERY, TEEN, NEWS, HISTORY, BIOGRAPHY,



}
